services:
  webapp-admin:
    build:
      context: ./apps/webapp-admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env.local
    depends_on:
      - supabase
      - redis
    volumes:
      - ./apps/webapp-admin:/app
      - /app/node_modules

  supabase:
    image: supabase/cli:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=howaiconnects
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  supabase_data:
  redis_data:
  qdrant_data: